from __future__ import annotations

import sqlite3
from typing import TYPE_CHECKING, Dict, List, Optional, Protocol, Sequence, Tuple

if TYPE_CHECKING:
    import numpy as np

from faiss_storage_lib.core.schema import VectorDocument


class IVectorIndex(Protocol):
    """Abstraction over a FAISS-backed vector index."""

    @property
    def ntotal(self) -> int: ...

    def add(self, vectors: np.ndarray, ids: np.ndarray) -> None: ...

    def remove(self, ids: List[int]) -> None: ...

    def search(self, query: np.ndarray, top_k: int) -> Tuple[np.ndarray, np.ndarray]: ...

    def reconstruct(self, int_id: int) -> List[float]: ...

    def rebuild(self, overrides: Dict[str, VectorDocument], uid_int_ids: Dict[str, int]) -> None: ...

    def persist(self, path: str) -> None: ...


class IDocumentDatabase(Protocol):
    """Abstraction over a SQLite-backed document store."""

    def ensure_schema(self) -> None: ...

    def upsert(self, rows: List[Tuple[str, int, str]]) -> None: ...

    def delete(self, uids: List[str]) -> None: ...

    def fetch_by_uid(self, uid: str) -> Optional[sqlite3.Row]: ...

    def fetch_by_int_ids(self, ids: Sequence[int]) -> Dict[int, sqlite3.Row]: ...

    def fetch_int_ids(self, uids: Sequence[str]) -> Dict[str, int]: ...

    def next_int_id(self) -> int: ...

    def fetch_all_uid_int_ids(self) -> List[sqlite3.Row]: ...

    def get_tracked_sources(self) -> Dict[str, List[str]]: ...

    def close(self) -> None: ...
